// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/send-magic-link": {
    params: {};
  };
  "/oauth/callback": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/notes": {
    params: {};
  };
  "/notes/:noteId": {
    params: {
      "noteId": string;
    };
  };
  "/notes/new": {
    params: {};
  };
  "/join": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/forgot-password" | "/send-magic-link" | "/oauth/callback" | "/reset-password" | "/healthcheck" | "/logout" | "/login" | "/notes" | "/notes/:noteId" | "/notes/new" | "/join";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/send-magic-link.tsx": {
    id: "routes/send-magic-link";
    page: "/send-magic-link";
  };
  "routes/oauth.callback.tsx": {
    id: "routes/oauth.callback";
    page: "/oauth/callback";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/healthcheck.tsx": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/notes.tsx": {
    id: "routes/notes";
    page: "/notes" | "/notes/:noteId" | "/notes/new";
  };
  "routes/notes.$noteId.tsx": {
    id: "routes/notes.$noteId";
    page: "/notes/:noteId";
  };
  "routes/notes._index.tsx": {
    id: "routes/notes._index";
    page: "/notes";
  };
  "routes/notes.new.tsx": {
    id: "routes/notes.new";
    page: "/notes/new";
  };
  "routes/join.tsx": {
    id: "routes/join";
    page: "/join";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "routes/send-magic-link": typeof import("./app/routes/send-magic-link.tsx");
  "routes/oauth.callback": typeof import("./app/routes/oauth.callback.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/healthcheck": typeof import("./app/routes/healthcheck.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/notes": typeof import("./app/routes/notes.tsx");
  "routes/notes.$noteId": typeof import("./app/routes/notes.$noteId.tsx");
  "routes/notes._index": typeof import("./app/routes/notes._index.tsx");
  "routes/notes.new": typeof import("./app/routes/notes.new.tsx");
  "routes/join": typeof import("./app/routes/join.tsx");
};